name: ifaa
publish_to: 'none'
description: Iranian Football Association Australia - Modern Flutter app template
version: 1.0.0+1
homepage: https://ali-emad.github.io/IFAA

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^16.2.1
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  google_sign_in: ^7.2.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  image_picker: ^1.2.0
  image: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/