name: ifaa_app
publish_to: 'none'
description: Iranian Football Association Australia - Modern Flutter app template
version: 1.0.0+1
homepage: https://ali-emad.github.io/IFAA

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/